#!/bin/sh
crpath=`pwd`
number=${1:-"NoNumber"}

if [[ "$crpath" == *information* ]]; then
    archivefile="information"
fi

if [[ "$crpath" == *experiment* ]]; then
    archivefile="experiment"
fi

if [[ "$crpath" == *analog* ]]; then
    archivefile="analogElectro"
fi

find $crpath/out -name "*.pdf" -type f -exec cp -f {} /Users/$USER/Desktop/${2:-"unknown"}.pdf \;

cd /Users/$USER/Documents/document/3rd-archive/$archivefile/
mkdir $number

cp -r -f $crpath/* ./$number

cd $crpath
find . -type f | xargs rm -f
rm -rf out


