#!/bin/sh

# ここからは固定
FNAME=$1
Title=${2:-'date'}
PDF=${1%.*}.pdf
Xlab=${3:-'Time t[s]'}
Ylab=${4:-'Voltage v[V]'}
Xrange=${5:-'*:*'}
Yrange=${6:-'*:*'}

gnuplot <<EOF
set term pdf color font 'Helvetica,14'
# set datafile separator whitespace
set datafile separator ","
set output '$PDF'

# ここからは自分で変更する部分
set key left top
set samples 500
set xzeroaxis
set yzeroaxis
set grid
set xlabel "$Xlab"
set ylabel "$Ylab"
set xrange [$Xrange]
set yrange [$Yrange]
# plot [-1:1] sin(2*pi*x) t 'v_a', sin(2*pi*x+2*pi/3) t 'v_b', sin(2*pi*x+4*pi/3) t 'v_c'
plot "$1" u 1:2 t '$Title' w l,"$1" u 1:3 t '$Title' w l,"$1" u 1:4 t '$Title' w l,"$1" u 1:5 t '$Title' w l,"$1" u 1:6 t '$Title' w l
# plot "$1" u 3:4 t 'parple' w p,"$1" u 7:8 t 'green' w p,"$1" u 5:6 t 'white' w p,"$1" u 1:2 t 'orange' w p

# ここからは固定
quit
EOF
open $PDF