#!/bin/sh
FORMAT=${3:-"JPG"}

if [ "$1" = "today" ]; then
    DATE=`date +%Y-%m-%d`
elif [ "$1" = "yesterday" ]; then
    DATE=`date -j -v-1d +"%Y-%m-%d"`
else
    DATE=${1:-`date +%Y-%m-%d`}
fi
echo "Serch the date:${DATE} extention:${FORMAT} Please Wait..."
REDATE=`echo ${DATE//-/:}`
PushFile="/Users/${USER}/Desktop/${REDATE}"
mkdir $PushFile

if [ "$2" = "here" ]; then
    find . -type f -name "*.${FORMAT}" -newermt "${DATE}" -exec cp -f {} $PushFile \;
else
    cd /Volumes/Untitled/DCIM
    find . -type f -name "*.${FORMAT}" -newermt "${DATE}" -exec cp -f {} $PushFile \;
fi
echo "succes full"